const SIGN_NAMES = [
  "Aries",
  "Taurus",
  "Gemini",
  "Cancer",
  "Leo",
  "Virgo",
  "Libra",
  "Scorpio",
  "Sagittarius",
  "Capricorn",
  "Aquarius",
  "Pisces",
];

const NAKSHATRA_NAMES = [
  "Ashwini",
  "Bharani",
  "Krittika",
  "Rohini",
  "Mrigashirsha",
  "Ardra",
  "Punarvasu",
  "Pushya",
  "Ashlesha",
  "Magha",
  "Purva Phalguni",
  "Uttara Phalguni",
  "Hasta",
  "Chitra",
  "Swati",
  "Vishakha",
  "Anuradha",
  "Jyeshtha",
  "Mula",
  "Purva Ashadha",
  "Uttara Ashadha",
  "Shravana",
  "Dhanishta",
  "Shatabhisha",
  "Purva Bhadrapada",
  "Uttara Bhadrapada",
  "Revati",
];

const DASA_LORDS = [
  "Ketu",
  "Venus",
  "Sun",
  "Moon",
  "Mars",
  "Rahu",
  "Jupiter",
  "Saturn",
  "Mercury",
];

const DASA_YEARS = {
  Ketu: 7,
  Venus: 20,
  Sun: 6,
  Moon: 10,
  Mars: 7,
  Rahu: 18,
  Jupiter: 16,
  Saturn: 19,
  Mercury: 17,
};

const TITHI_NAMES = [
  "Pratipada",
  "Dwitiya",
  "Tritiya",
  "Chaturthi",
  "Panchami",
  "Shashthi",
  "Saptami",
  "Ashtami",
  "Navami",
  "Dashami",
  "Ekadashi",
  "Dwadashi",
  "Trayodashi",
  "Chaturdashi",
  "Purnima",
];

const AVAKHADA_MAP = [
  {
    varna: "Kshatriya",
    vashya: "Chatushpada",
    yoni: "Ashwa",
    gana: "Deva",
    nadi: "Adi",
    tatwa: "Vayu",
  },
  {
    varna: "Shudra",
    vashya: "Chatushpada",
    yoni: "Gaja",
    gana: "Manushya",
    nadi: "Madhya",
    tatwa: "Prithvi",
  },
  {
    varna: "Brahmin",
    vashya: "Chatushpada",
    yoni: "Mesh",
    gana: "Rakshasa",
    nadi: "Antya",
    tatwa: "Agni",
  },
  {
    varna: "Vaishya",
    vashya: "Chatushpada",
    yoni: "Sarpa",
    gana: "Manushya",
    nadi: "Adi",
    tatwa: "Prithvi",
  },
  {
    varna: "Shudra",
    vashya: "Chatushpada",
    yoni: "Sarpa",
    gana: "Deva",
    nadi: "Madhya",
    tatwa: "Prithvi",
  },
  {
    varna: "Vaishya",
    vashya: "Manava",
    yoni: "Shwan",
    gana: "Manushya",
    nadi: "Antya",
    tatwa: "Vayu",
  },
  {
    varna: "Kshatriya",
    vashya: "Manava",
    yoni: "Marjara",
    gana: "Deva",
    nadi: "Adi",
    tatwa: "Vayu",
  },
  {
    varna: "Kshatriya",
    vashya: "Manava",
    yoni: "Mesh",
    gana: "Deva",
    nadi: "Madhya",
    tatwa: "Jala",
  },
  {
    varna: "Brahmin",
    vashya: "Jalachara",
    yoni: "Marjara",
    gana: "Rakshasa",
    nadi: "Antya",
    tatwa: "Jala",
  },
  {
    varna: "Shudra",
    vashya: "Manava",
    yoni: "Mushaka",
    gana: "Rakshasa",
    nadi: "Adi",
    tatwa: "Agni",
  },
  {
    varna: "Brahmin",
    vashya: "Manava",
    yoni: "Mushaka",
    gana: "Manushya",
    nadi: "Madhya",
    tatwa: "Agni",
  },
  {
    varna: "Kshatriya",
    vashya: "Manava",
    yoni: "Gau",
    gana: "Manushya",
    nadi: "Antya",
    tatwa: "Agni",
  },
  {
    varna: "Brahmin",
    vashya: "Manava",
    yoni: "Mahisha",
    gana: "Deva",
    nadi: "Adi",
    tatwa: "Jala",
  },
  {
    varna: "Shudra",
    vashya: "Vanachara",
    yoni: "Vyaghra",
    gana: "Rakshasa",
    nadi: "Madhya",
    tatwa: "Agni",
  },
  {
    varna: "Brahmin",
    vashya: "Vanachara",
    yoni: "Mahisha",
    gana: "Deva",
    nadi: "Antya",
    tatwa: "Vayu",
  },
  {
    varna: "Brahmin",
    vashya: "Manava",
    yoni: "Vyaghra",
    gana: "Rakshasa",
    nadi: "Adi",
    tatwa: "Agni",
  },
  {
    varna: "Shudra",
    vashya: "Manava",
    yoni: "Mriga",
    gana: "Deva",
    nadi: "Madhya",
    tatwa: "Jala",
  },
  {
    varna: "Shudra",
    vashya: "Manava",
    yoni: "Mriga",
    gana: "Rakshasa",
    nadi: "Antya",
    tatwa: "Jala",
  },
  {
    varna: "Brahmin",
    vashya: "Vanachara",
    yoni: "Shwan",
    gana: "Rakshasa",
    nadi: "Adi",
    tatwa: "Vayu",
  },
  {
    varna: "Kshatriya",
    vashya: "Vanachara",
    yoni: "Vanara",
    gana: "Manushya",
    nadi: "Madhya",
    tatwa: "Vayu",
  },
  {
    varna: "Kshatriya",
    vashya: "Vanachara",
    yoni: "Nakula",
    gana: "Manushya",
    nadi: "Antya",
    tatwa: "Vayu",
  },
  {
    varna: "Shudra",
    vashya: "Vanachara",
    yoni: "Vanara",
    gana: "Deva",
    nadi: "Adi",
    tatwa: "Jala",
  },
  {
    varna: "Shudra",
    vashya: "Rakshasa",
    yoni: "Simha",
    gana: "Rakshasa",
    nadi: "Madhya",
    tatwa: "Agni",
  },
  {
    varna: "Brahmin",
    vashya: "Rakshasa",
    yoni: "Ashwa",
    gana: "Rakshasa",
    nadi: "Antya",
    tatwa: "Akasha",
  },
  {
    varna: "Brahmin",
    vashya: "Manava",
    yoni: "Simha",
    gana: "Manushya",
    nadi: "Adi",
    tatwa: "Akasha",
  },
  {
    varna: "Kshatriya",
    vashya: "Manava",
    yoni: "Gau",
    gana: "Manushya",
    nadi: "Madhya",
    tatwa: "Akasha",
  },
  {
    varna: "Vaishya",
    vashya: "Manava",
    yoni: "Gau",
    gana: "Deva",
    nadi: "Antya",
    tatwa: "Jala",
  },
];

const DIGNITY_TABLE = {
  Sun: {
    own: [5],
    exaltation: 1,
    debilitation: 7,
    friends: [1, 4, 9],
    enemies: [2, 10, 11, 6],
  },
  Moon: {
    own: [4],
    exaltation: 2,
    debilitation: 8,
    friends: [1, 4, 5],
    enemies: [9, 10, 11],
  },
  Mars: {
    own: [1, 8],
    exaltation: 10,
    debilitation: 4,
    friends: [1, 4, 5],
    enemies: [2, 6],
  },
  Mercury: {
    own: [3, 6],
    exaltation: 6,
    debilitation: 12,
    friends: [3, 6, 7],
    enemies: [5, 9],
  },
  Jupiter: {
    own: [9, 12],
    exaltation: 4,
    debilitation: 10,
    friends: [1, 4, 5],
    enemies: [2, 6, 7],
  },
  Venus: {
    own: [2, 7],
    exaltation: 12,
    debilitation: 6,
    friends: [2, 7, 10],
    enemies: [5, 9],
  },
  Saturn: {
    own: [10, 11],
    exaltation: 7,
    debilitation: 1,
    friends: [2, 6, 7],
    enemies: [1, 4, 5],
  },
};

module.exports = {
  zodiac: {
    SIGN_NAMES,
    NAKSHATRA_NAMES,
    DIGNITY_TABLE,
  },
  dasha: {
    DASA_LORDS,
    DASA_YEARS,
  },
  tithi: {
    TITHI_NAMES,
  },
  compatibility: {
    AVAKHADA_MAP,
  },
};
